const users = [
  
      {
        "id": 1,
        "name": "Carlos López",
        "dni": 12345678,
        "email": "carlos@example.com",
        "password": "mypassword",
        "address": "123 main st",
        "city": "Metropolis",
        "country": "Country",
        "rol": "candidate",
        "suffrage": true,
        
      },
      {
        "id": 2,
        "name": "María González",
        "dni": 23456789,
        "email": "maria@example.com",
        "password": "mypassword",
        "address": "456 elm st",
        "city": "Gotham",
        "country": "Country",
        "rol": "candidate",
        "suffrage": true,
      },
      {
        "id": 3,
        "name": "Luis Rodríguez",
        "dni": 34567890,
        "email": "luis@example.com",
        "password": "mypassword",
        "address": "789 oak st",
        "city": "Star City",
        "country": "Country",
        "rol": "candidate",
        "suffrage": true,
      },
      {
        "id": 4,
        "name": "Ana Torres",
        "dni": 45678901,
        "email": "ana@example.com",
        "password": "mypassword",
        "address": "101 pine st",
        "city": "Central City",
        "country": "Country",
        "rol": "candidate",
        "suffrage": true,
      },
      {
        "id": 5,
        "name": "Pedro Pérez",
        "dni": 56789012,
        "email": "pedro@example.com",
        "password": "mypassword",
        "address": "202 maple st",
        "city": "Coast City",
        "country": "Country",
        "rol": "candidate",
        "suffrage": true
      },
      {
        "id": 6,
        "name": "Julia Martínez",
        "dni": 67890123,
        "email": "julia@example.com",
        "password": "mypassword",
        "address": "303 birch st",
        "city": "Blüdhaven",
        "country": "Country",
        "rol": "candidate",
        "suffrage": true,
      },
      {
        "id": 7,
        "name": "Andrés Fernández",
        "dni": 78901234,
        "email": "andres@example.com",
        "password": "mypassword",
        "address": "404 cedar st",
        "city": "National City",
        "country": "Country",
        "rol": "candidate",
        "suffrage": true,
      },
      {
        "id": 8,
        "name": "Clara Hernández",
        "dni": 89012345,
        "email": "clara@example.com",
        "password": "mypassword",
        "address": "505 walnut st",
        "city": "Metropolis",
        "country": "Country",
        "rol": "candidate",
        "suffrage": true,
      },
      {
        "id": 9,
        "name": "David Castillo",
        "dni": 90123456,
        "email": "david@example.com",
        "password": "mypassword",
        "address": "606 chestnut st",
        "city": "Gotham",
        "country": "Country",
        "rol": "candidate",
        "suffrage": true,
      },
      {
        "id": 10,
        "name": "Sofía Ruiz",
        "dni": 11234567,
        "email": "sofia@example.com",
        "password": "mypassword",
        "address": "707 spruce st",
        "city": "Star City",
        "country": "Country",
        "rol": "candidate",
        "suffrage": true,
      }
      
    ]
  
export default users