import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/navBar/NavBar";
import Footer from "@/components/footer/Footer";
import { AuthProvider } from "@/context/Authontext";
import { GuideProvider } from "@/context/GuideContext";
import {UserProvider} from '@auth0/nextjs-auth0/client'
import Dashboard from "@/components/dashboard/Dashboard";


export const metadata: Metadata = {
  title: "Voting System",
  description: "Generated by Group 1",
  icons: "https://res.cloudinary.com/dgexsgnid/image/upload/v1727442964/Logo%20solo.png"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  

  return (
    <html lang="en">
      <body>
        <UserProvider>
        <AuthProvider>
          <GuideProvider>
            <div className="containerPrincipal">
              <header>
                <NavBar />
              </header>
              <main className="mt-14">
                  <div> <Dashboard/> </div> 
                  {children}
              </main>
              <footer>
                <Footer />
              </footer>
            </div>
          </GuideProvider>
        </AuthProvider>
        </UserProvider>
      </body>
    </html>
  );
}