import type { Metadata } from "next";
import "./globals.css";

import NavBar from "@/components/navBar/NavBar";
import Footer from "@/components/footer/Footer";
import { AuthProvider } from "@/context/Authontext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
<AuthProvider>
        
        <div className="containerPrincipal">
          <header>
            <NavBar />
          </header>
          <main className="mt-14">
            {children}
          </main>
          <footer>
            <Footer/>
          </footer>
        </div>
</AuthProvider>
      </body>
    </html>
  );
}